facebook:
  client:
    clientId: nnsmadnsm
    clientSecret: gshdgashgdhgsdjsgjd
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: sjdnasdnsm
    clientSecret: jshdjashdkjshjkdhskjdh
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
ownserver: 
  client:
    clientId: fooClientIdPassword
    clientSecret: secret
    accessTokenUri: http://localhost:8081/oauth-server/oauth/token
    userAuthorizationUri: http://localhost:8081/oauth-server/oauth/authorize
    clientAuthenticationScheme: header
    authentication-scheme: form
    token-name: token
  resource:
    userInfoUri: http://localhost:8081/oauth-server/oauth/check_token
logging:
  level:
    org.springframework.security: DEBUG
